# Generated by Django 4.0.2 on 2023-02-16 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0004_alter_property_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='total_area',
            field=models.CharField(max_length=10),
        ),
    ]
