# Generated by Django 4.0.2 on 2023-02-18 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0007_city_remove_advertisement_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='sold',
            field=models.BooleanField(default=False),
        ),
    ]
