# Generated by Django 4.0.2 on 2023-02-21 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0008_alter_advertisement_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='house',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
