# Generated by Django 4.0.2 on 2023-02-21 13:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0009_alter_advertisement_house'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='apartment',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0, 'Price can not be negative')]),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='total_area',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
