# Generated by Django 4.0.2 on 2023-02-21 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0010_alter_advertisement_apartment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='apartment',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='total_area',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='realtor',
            name='phone_number',
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name='realtor',
            name='years_of_experience',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
