# Generated by Django 4.0.2 on 2023-02-21 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0011_alter_advertisement_apartment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
