# Generated by Django 4.0.2 on 2023-02-24 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0012_alter_realtor_phone_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Property',
            new_name='PropertyType',
        ),
        migrations.RenameField(
            model_name='advertisement',
            old_name='property',
            new_name='property_type',
        ),
    ]
